version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: flaskApi
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flaskPassword
    ports:
      - "5431:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: